# Generated by Django 5.2.8 on 2025-11-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
