# Generated by Django 5.2.8 on 2025-11-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
