# Generated by Django 5.2.8 on 2025-11-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_name',
            field=models.CharField(choices=[('COURSE_ENROLLED', 'Course Enrolled'), ('COURSE_50_PERCENT', 'Course 50% Completed'), ('COURSE_COMPLETED', 'Course Completed'), ('USER_REGISTERED', 'User Registered'), ('USER_FORGOT_PASSWORD', 'Forgot Password Requested'), ('USER_PASSWORD_RESET', 'Password Reset Success')], max_length=50, unique=True),
        ),
    ]
